jQuery(document).ready(function(){!function(m){function a(a,e){m(".p-attendance-check .p-attendance-check__days > li").remove();// remove only in days
var n=y(a,e),t=p(a,e),c=["01","02","03","04","05","06","07","08","09","10","11","12"],o=m(".p-attendance-check__clone > .p-attendance-check__days__date--no_seal"),_=m(".p-attendance-check__clone > .p-attendance-check__days__date--yes_seal"),d=m(".p-attendance-check__days"),r=35-(t+n);r<0&&(r=t),m(".p-attendance-check__header__monthname").text(a+"."+c[e-1]);for(var s=0;s<t;s++)d.append(m('<li class="empty">&nbsp;</li>'));for(var s=1;s<=n;s++){var i=o.clone();if(u(s,e,a)&&(i=_.clone()),i.find(".p-attendance-check__days__date__number").text(s),l(s,e,a)&&(i.addClass("p-attendance-check__days__date--today"),!i.hasClass("p-attendance-check__days__date--yes_seal"))){var h=k.clone(!0);i.append(h)}d.append(i)}for(var s=0;s<r;s++)d.append(m('<li class="empty">&nbsp;</li>'))}function p(a,e){var n;return e<10&&(e="0"+e),moment(a+"-"+e+"-01 00:00:00").weekday()}function y(a,e){return e<10&&(e="0"+e),moment(a+"-"+e,"YYYY-MM").daysInMonth()}function l(a,e,n){return a==c.day&&e==c.month&&n==c.year}function u(a,e,n){return void 0!==t[n]&&void 0!==t[n][e]&&void 0!==t[n][e][a]}var e;if(0<m(".p-attendance-check").length){var t=m(".p-attendance-check").data("history"),c={year:moment().year(),month:moment().month()+1,day:moment().date()};pac_ajax_obj.test_mode&&(c.year-=pac_ajax_obj.year_minus,c.month-=pac_ajax_obj.month_minus,c.day-=pac_ajax_obj.day_minus);var n=c.year,o=c.month,k=m(".p-attendance-check__stamp_btn");k.on("click",function(){var e=m(this);if(!e.hasClass("loading")){e.addClass("loading");var a={action:"attendance_check",check_today:!0};m.post(pac_ajax_obj.ajax_url,a,function(a){200==a.code?(e.hide(),e.siblings("img")[0].src=pac_ajax_obj.seal_src,
// 완전 처음 들어온경우
t||((t=[])[c.year]=[],t[c.year][c.month]=[]),
// 처음 들어온건 아니지만, year이 없는 경우
void 0===t[c.year]&&(t[c.year]=[],t[c.year][c.month]=[]),
// year은 있는데 month가 없는경우
void 0===t[c.year][c.month]&&(t[c.year][c.month]=[]),
// day는 당연히 없겠지! 이제 넣자!
t[c.year][c.month][c.day]=!0,e.remove()):e.removeClass("loading"),alert(a.message)},"json")}}),a(n,o),m(".p-attendance-check__header__pointer--minusmonth .fas").click(function(){0==(o-=1)&&(n-=1,o=12),a(n,o)}),m(".p-attendance-check__header__pointer--addmonth .fas").click(function(){12==(o+=1)&&(n+=1,o=1),a(n,o)})}}(jQuery)});
//# sourceMappingURL=main-min.js.map